author: Javhu # 作者
description: Javhu的博客
keyword: hexo-theme, vuejs
favicon: 

excerpt_link: 展开

menu:
 首页: /
 标签: /tags/
 归档: /archives/
 项目: /project/
 关于: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set gitment, uyan or disqus
comment: gitment

# gitment config
gitment_owner: Javhu
gitment_repo: hexo_comments
gitment_oauth_id: ebef9476f10fb6260605
gitment_oauth_secret: f1e347e9b74201ec8629cf1667cd450ba469dcb1

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
#baidu_id: 
#google_analytics:
# disqus config
#disqus_shortname: 

about: 
  banner: http://file.muyutech.com/about.jpg
  avatar: https://avatars3.githubusercontent.com/u/16443628?v=3&s=460
  description: "不试试怎么知道你是真的不会还是假的会"
  weibo_username: 储小V
  twitter_username: javhu
  github_username: Javhu
  zhihu_username: javhu
  douban_username: javhu
  linkedin_username: javhu

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML
